### ISSUE TITLE
[Bug] Tutorial 4 and 5 crash

### ISSUE THREAD

**Issue by af1990** [GEOSX/GEOSX#1121] opened 2020-08-22 19:05 UTC
**Description**
Tutorials [4](https://geosx-geosx.readthedocs-hosted.com/en/latest/docs/sphinx/tutorials/step04/Tutorial.html) and [5](https://geosx-geosx.readthedocs-hosted.com/en/latest/docs/sphinx/tutorials/step05/Tutorial.html) are able to solve the first time step fine but then crash during the VTK output, with the error:
```
***** LOCATION: src/coreComponents/common/DataTypes.hpp:920
***** Controlling expression (should be false): true
***** Rank 0: TypeID not recognized.

** StackTrace of 8 frames **
Frame 0: geosx::vtk::VTKPolyDataWriterInterface::WriteField(geosx::dataRepository::WrapperBase const&, vtkSmartPointer<geosx::vtk::VTKGEOSXData>, long, long&) const 
Frame 1: void geosx::vtk::VTKPolyDataWriterInterface::WriteElementFields<geosx::CellElementSubRegion>(vtkSmartPointer<vtkCellData>, geosx::ElementRegionBase const&) const 
Frame 2: geosx::vtk::VTKPolyDataWriterInterface::WriteCellElementRegions(double, geosx::ElementRegionManager const&, geosx::NodeManager const&) const 
Frame 3: geosx::vtk::VTKPolyDataWriterInterface::Write(double, int, geosx::DomainPartition const&) 
Frame 4: geosx::EventBase::Execute(double, double, int, int, double, geosx::dataRepository::Group*) 
Frame 5: geosx::EventManager::Run(geosx::dataRepository::Group*) 
Frame 6: main 
Frame 7: __libc_start_main 
Frame 8: _start 
=====
```

**To Reproduce**
1. checkout the `develop` branch
2. compile with any LAI
3. run one of the two tutorials as described in the documentation
4. enjoy the error

**Expected behavior**
It should work.

**Platform**
I do not think this is platform dependent.

**Additional context**
This error was first noticed by @juliatcamargo.
I think the issue is this field, defined in `CompositionalMultiphaseReservoir`:
https://github.com/GEOSX/GEOSX/blob/aa4b4d1389329eb44219c3f7596c299be8a76146/src/coreComponents/physicsSolvers/multiphysics/CompositionalMultiphaseReservoir.cpp#L184-L185

the problem is that the generic _lambda launcher_ `ApplyArrayTypeLambda2` does not provide any action for a 4d array, just the error `TypeID not recognized.`
https://github.com/GEOSX/GEOSX/blob/aa4b4d1389329eb44219c3f7596c299be8a76146/src/coreComponents/common/DataTypes.hpp#L834-L836
https://github.com/GEOSX/GEOSX/blob/aa4b4d1389329eb44219c3f7596c299be8a76146/src/coreComponents/common/DataTypes.hpp#L918-L921

**Comment by AntoineMazuyer** [comment] 2020-08-27 14:06
Duplicate of #1112

**Closed by AntoineMazuyer** 2020-08-27 14:06 UTC
Labels: new
