### ISSUE TITLE
[Bug] The entries reported by `TimeHistory` when collection and output async.

### ISSUE THREAD

**Issue by jafranc** [GEOSX/GEOSX#1851] opened 2022-03-26 00:29 UTC
**Describe the bug**
The entries reported by `TimeHistory` when _collection_ event is asynchronized with _output_ event are erroneous.

**To Reproduce**
1. Unzip __sm_class09.zip__[sm_cases.zip](https://github.com/GEOSX/GEOSX/files/8447643/sm_cases.zip)  
2. Run with __class09_sync.xml__ with blocks as

```
 <Events
   <PeriodicEvent
      name="timeRhoHistoryCollection"
      timeFrequency=".1e7"
      targetExactTimestep="1"
      target="/Tasks/rhoCollection" />
   <PeriodicEvent
      name="timeRhoHistoryOutput"
      timeFrequency=".1e7"
      targetExactTimestep="1"
      target="/Outputs/timeRhoHistoryOutput" />
</Events>
```
3. Plot data using __postt_class09_3.py__ which reports for two component sum of cell entries for all three collected vars (saturation, densities, componentFraction)
5. Run with __class09_sync.xml__ with blocks as
```
 <Events
   <PeriodicEvent
      name="timeRhoHistoryCollection"
       timeFrequency=".1e7"
      targetExactTimestep="1"
      target="/Tasks/rhoCollection" />
   <PeriodicEvent
      name="timeRhoHistoryOutput"
      timeFrequency="1e7" 
      targetExactTimestep="1"
      target="/Outputs/timeRhoHistoryOutput" />
</Events>
```
6. Repeat 3.

**Expected behavior**
Both cases should produce the same **hdf5** collected solution, collected with different strategies regarding output.

**Platform (please complete the following information):**
- Machine Ubuntu 18.04
- Compiler: gcc 10.x.x
- GEOSX Version [877758e65]

**Notes**
~~In the `timeHistory` output values are reorganized depending on the variable, _e.g._ for _densities_ or _componentFraction_ are ordered colwise as [ _Time_, _coords_, _value_ ] while _phaseVolumeFraction_  starts with [ _value_ , ..etc]~~

**Comment by TotoGaz** [comment] 2022-04-08 00:12
@jafranc I cannot find `class09_sync.xml` you mention (it's not in the `zip`, for instance).
I expect it to be some tutorial or something like... Could you help me?

**Comment by jafranc** [comment] 2022-04-08 00:40
It is a smaller version of Class09 Pb#3 on Johansen mesh, but should be reproducible on simpler case if you want me to set up one ?  I updated the zip with the correct material.

**Comment by TotoGaz** [comment] 2022-04-08 04:28
@wrtobin Do you think that this actually is a bug? I'm actually not sure and maybe this is the intended behavior?

**Comment by wrtobin** [comment] 2022-04-08 05:03
If you have a collection operation occurring every .1e7 versus one every 1e7 I would expect the prior to collect 10 times as often as the latter and thus have 10 times the number of rows in the hdf output files. Having an output that occurs 10 times more often than the collection also won't result in anything other than a potential performance hit. In general an output should occur less often than a collection, as the collection is internally buffered until an output happens.

re the note: internally we only ever create the hdf arrays with 1st index time and 2nd index related to the mesh object indices, are you certain the 3rd array is indexed as values with time and mesh relationship as subsequent indices? That would be quite odd unless hdf itself is making the changes under the hood for some reason. If you have an hdf file exhibiting that structuring could you post it?

**Comment by TotoGaz** [comment] 2022-04-08 13:50
> If you have a collection operation occurring every .1e7 versus one every 1e7 I would expect the prior to collect 10 times as often as the latter and thus have 10 times the number of rows in the hdf output files. 

So this is no surprise that in this case we get to times less data than from the other?

> Having an output that occurs 10 times more often than the collection also won't result in anything other than a potential performance hit. In general an output should occur less than or just as often as a collection, as the collection is internally buffered until an output happens.

Is there a way to control the writing of the dumping and a way to control the collection?

**Comment by wrtobin** [comment] 2022-04-08 15:10
Yes the description as written implies that they should expect on output with 10 times as much data, no bug.

The cadence/frequency is done through the event triggering only. It is possible to specify specific times using multiple single events instead of on repeating event, or they can be used in tandem. Same with collections. That is why they are separate objects from the events, so they should be able to be targeted and triggered by multiple events for less conventional collection paradigms. If we need finer-grained control in some way a "smart"-event might be possible where the event re-schedules itself with the event-loop based on some internal decision making process.

**Comment by TotoGaz** [comment] 2022-04-08 15:18
OK thx for your help @wrtobin 
@jafranc are you OK with this or is there anything else you are trying to achieve and you can't?
Otherwise we may close this issue? Or convert it into a feature request if you can't reach your goals.

**Comment by jafranc** [comment] 2022-04-08 15:19
Apologies, I introduced a typo in the issue presentation (but not in the test case files). I was attempting to oversample the `collection` over the `output` (and not the over way around).

**Comment by wrtobin** [comment] 2022-04-08 15:27
Looking at the files, one of the collections occurs every 1e7 and one every .1e7, so I would still expect that the one that collects more often would have 10x as much data. 

The collection retains a sample of the current state in a buffer, that state is not retained unless it is collected. 

So each time the collection is triggered by an event it collects *one* row of the current state at the time it was triggered.

**Comment by wrtobin** [comment] 2022-04-08 15:31
Ah yes okay, after the edit to add the graphs, clearly there is a bug. Are you possibly targeting the same output directory so an existing time-history file is being accessed on a subsequent run, there is some checking for that which should prohibit it happening unless it is a restart, but I want to eliminate an external possibility before we recreate.

**Comment by jafranc** [comment] 2022-04-08 15:38
Just re-run the case discarding every `*.hdf5`, I still got the oscillatory output after post-process.

**Comment by TotoGaz** [comment] 2022-04-08 15:42
When I do
```python
import h5py

rha = h5py.File("output-async/rhoHistory.hdf5", 'r')
rhs = h5py.File("output-sync/rhoHistory.hdf5", 'r')

rha['fluid_phaseDensity Time'][90][0] # prints 90000000.0
rhs['fluid_phaseDensity Time'][9][0] # prints 90000000.0

rha['fluid_phaseDensity'][90][0] # prints array([1042.89237477,  803.18412976])
rhs['fluid_phaseDensity'][9][0] # prints array([ 730.28536703, 1028.81923265])
```

Is this what you mean?

**Comment by jafranc** [comment] 2022-04-08 15:56
On the note: double checking, I failed to find former output with the re-arranged columns and current output are all uniformly col-wise ordered. Must have been mistaken. Apologies.

**Comment by TotoGaz** [comment] 2022-04-08 15:59
@jafranc You do expect the `sync` version to be the correct one? (By checking some `vtk` or `silo` outputs)?

**Comment by jafranc** [comment] 2022-04-08 15:59
`sync` version provides the correct values

**Comment by TotoGaz** [comment] 2022-04-11 19:22
I've tested my own buffer implementation and for `fluid_phaseDensity` I can get
```
  1 660.978 1024.57
  2 690.405 1026.19
  3 714.734 1027.72
  4 730.285 1028.81
  5 730.285 1028.81
  6 730.285 1028.81
  7 730.285 1028.81
  8 730.285 1028.81
  9 730.285 1028.82
 10 730.285 1028.82
```
for the `sync` case and for the `async` case I get the following
```
  1 660.978 1024.57
  2 665.283 1024.79
  3 668.556 1024.97
  4 671.408 1025.12
  5 673.928 1025.25
  6 676.757 1025.41
  7 679.792 1025.58
  8 682.666 1025.74
  9 685.455 1025.9
 10 688.108 1026.06
 11 690.675 1026.21
 12 693.108 1026.35
 13 695.553 1026.5
 14 698.043 1026.65
 15 700.59 1026.81
 16 703.098 1026.97
 17 705.58 1027.13
 18 708.002 1027.28
 19 710.383 1027.44
 20 712.71 1027.59
 21 714.987 1027.74
 22 717.23 1027.89
 23 719.428 1028.04
 24 721.588 1028.19
 25 723.705 1028.34
 26 725.805 1028.49
 27 727.892 1028.64
 28 730.041 1028.79
 29 730.285 1028.81
 30 730.285 1028.81
... SNIP ...
 84 730.285 1028.81
 85 730.285 1028.82
... SNIP ...
100 730.285 1028.82
```
So we can witness small variations (is it legit?) but furthermore, not these buggy oscillations.
@wrtobin do you think something could be wrong in `HDFHistIO`. You can test my branch `bugfix/TotoGaz/TimeHistory` if you want.

For the record, I have this for `hdf5` in the `async` case
```
  1 [ 660.97849016 1024.5692363 ]
  2 [ 665.28277822 1024.79199726]
  3 [1038.17107266  734.18819962]
  4 [ 668.55631531 1024.9652517 ]
  5 [1038.36735603  737.64848217]
  6 [ 671.40763582 1025.11802479]
  7 [1038.52986911  740.48126781]
  8 [ 673.92800861 1025.25496287]
  9 [1038.66989292  742.87018773]
 10 [ 676.75731447 1025.41056268]
 11 [1038.82050629  745.39419112]
 12 [ 693.10789361 1026.35384471]
 13 [1039.74019245  760.04043868]
 14 [ 695.55281895 1026.50070802]
 15 [1039.88086272  762.18503236]
 16 [ 698.0433762  1026.65380356]
 17 [1040.02729961  764.3616626 ]
 18 [ 700.59002342 1026.81091431]
 19 [1040.179155    766.61253252]
 20 [ 703.09801134 1026.96870585]
 21 [1040.33312071  768.84622686]
 22 [ 717.23035864 1027.8926241 ]
 23 [1041.22860169  781.35408137]
 24 [ 719.42777789 1028.04260258]
 25 [1041.37338823  783.28990269]
 26 [ 721.58827112 1028.19111756]
 27 [1041.51696915  785.19294912]
 28 [ 723.70493366 1028.33888167]
 29 [1041.65985807  787.05986949]
 30 [ 725.80465544 1028.48629657]
 31 [1041.80205792  788.90436837]
 32 [ 730.28536703 1028.8068259 ]
 33 [1042.89237477  803.18412976]
 34 [ 730.28536703 1028.80684459]
 35 [1042.89237477  803.18412976]
 36 [ 730.28536703 1028.8068663 ]
 37 [1042.89237477  803.18412976]
 38 [ 730.28536703 1028.80689082]
 39 [1042.89237477  803.18412976]
 40 [ 730.28536703 1028.80691805]
 41 [1042.89237477  803.18412976]
 42 [ 730.28536703 1028.80720677]
 43 [1042.89237477  803.18412976]
 44 [ 730.28536703 1028.80727965]
 45 [1042.89237477  803.18412976]
 46 [ 730.28536703 1028.80735919]
 47 [1042.89237477  803.18412976]
 48 [ 730.28536703 1028.8074448 ]
 49 [1042.89237477  803.18412976]
 50 [ 730.28536703 1028.80753546]
 51 [1042.89237477  803.18412976]
 52 [ 730.28536703 1028.80814604]
 53 [1042.89237477  803.18412976]
 54 [ 730.28536703 1028.80825663]
 55 [1042.89237477  803.18412976]
 56 [ 730.28536703 1028.8083696 ]
 57 [1042.89237477  803.18412976]
 58 [ 730.28536703 1028.80848415]
 59 [1042.89237477  803.18412976]
 60 [ 730.28536703 1028.8086001 ]
 61 [1042.89237477  803.18412976]
 62 [ 730.28536703 1028.8093478 ]
 63 [1042.89237477  803.18412976]
 64 [ 730.28536703 1028.80949634]
 65 [1042.89237477  803.18412976]
 66 [ 730.28536703 1028.80965748]
 67 [1042.89237477  803.18412976]
 68 [ 730.28536703 1028.80983424]
 69 [1042.89237477  803.18412976]
 70 [ 730.28536703 1028.81003011]
 71 [1042.89237477  803.18412976]
 72 [ 730.28536703 1028.81140507]
 73 [1042.89237477  803.18412976]
 74 [ 730.28536703 1028.81165657]
 75 [1042.89237477  803.18412976]
 76 [ 730.28536703 1028.81191384]
 77 [1042.89237477  803.18412976]
 78 [ 730.28536703 1028.81217615]
 79 [1042.89237477  803.18412976]
 80 [ 730.28536703 1028.81244426]
 81 [1042.89237477  803.18412976]
 82 [ 730.28536703 1028.81416037]
 83 [1042.89237477  803.18412976]
 84 [ 730.28536703 1028.8144602 ]
 85 [1042.89237477  803.18412976]
 86 [ 730.28536703 1028.81476366]
 87 [1042.89237477  803.18412976]
 88 [ 730.28536703 1028.81506997]
 89 [1042.89237477  803.18412976]
 90 [ 730.28536703 1028.81537831]
 91 [1042.89237477  803.18412976]
 92 [ 730.28536703 1028.81723568]
 93 [1042.89237477  803.18412976]
 94 [ 730.28536703 1028.8175476 ]
 95 [1042.89237477  803.18412976]
 96 [ 730.28536703 1028.81786164]
 97 [1042.89237477  803.18412976]
 98 [ 730.28536703 1028.81817632]
 99 [1042.89237477  803.18412976]
100 [ 730.28536703 1028.81849144]
```

**Comment by jafranc** [comment] 2022-04-11 20:25
@TotoGaz I would expect variation in this case as the density is dependent of local properties (pressure, temperature, composition...)

**Comment by TotoGaz** [comment] 2022-04-11 20:32
Variations between `sync` and `async`? But values from `async` are crooked anyway...

**Comment by jafranc** [comment] 2022-04-11 20:39
Variations internal to `sync` and `async`. Thoughif comparing lines 2: from `sync` and 11: from `async`,
```
(sync)      2 690.405 1026.19
 (async) 11 690.675 1026.21
```
values are slightly different but could be explain by the fact that `sync` is maybe allowed to take larger time step while `async` is retrained by collection frequency, hence a larger time discretization error on `sync` ? 
What happen if both run are forced to take the same maximum time-steps which is less than the minimal collection frequency (`.1e7`) ?

**Comment by TotoGaz** [comment] 2022-04-11 21:45
@jafranc Yes I can get
```
1 660.978 1024.57
2 690.675 1026.21
3 714.987 1027.74
```
with `sync` and a little time step while keeping a larger collection.
So it looks consistent. 🎉

**Closed** 2022-05-14 01:49 UTC
Labels: type: bug
