### ISSUE TITLE
Syntax error in the gravityVector in xml file cannot be detected

### ISSUE THREAD

**Issue by jhuang2601** [GEOSX/GEOSX#1514] opened 2021-07-23 19:04 UTC
In xml file, brackets are required for the gravityVector `<Solvers gravityVector="{0.0, 0.0, 0.0}">`.

However, if wrongly removing the curly brackets `{`,  XML validation step will overlook this problem and case can be still running and no issue is reported.  When building this PR ( #1474 ), it failed and this issue was recognized.

To avoid this unexpected build failure, the XML validation step should be enforced to check the syntax of the gravityVector, when running the cases.

**Comment by cssherman** [comment] 2021-07-23 21:01
@jhuang2601 - I've checked this under the develop branch, and the schema catches problems with brackets (and other similar R1Tensor types).  For example, removing the open bracket from the solid mechanics "gravity.xml" test yields the following error:

```
[100%] Built target geosx_update_rst_tables
/usr/WS2/sherman/GEOSX/src/coreComponents/physicsSolvers/solidMechanics/integratedTests/gravity.xml:19: element Solvers: Schemas validity error : Element 'Solvers', attribute 'gravityVector': [facet 'pattern'] The value '0.0, 0.0, -9.81}' is not accepted by the pattern '.*[\[\]`$].*|\s*\{\s*([+-]?[\d]*([\d]\.?|\.[\d])[\d]*([eE][-+]?[\d]+|\s*),\s*){2}[+-]?[\d]*([\d]\.?|\.[\d])[\d]*([eE][-+]?[\d]+|\s*)\s*\}'.
/usr/WS2/sherman/GEOSX/src/coreComponents/physicsSolvers/solidMechanics/integratedTests/gravity.xml:19: element Solvers: Schemas validity error : Element 'Solvers', attribute 'gravityVector': '0.0, 0.0, -9.81}' is not a valid value of the atomic type 'R1Tensor'.
/usr/WS2/sherman/GEOSX/src/coreComponents/physicsSolvers/solidMechanics/integratedTests/gravity.xml fails to validate
XML validation failed. See details in xml_validation_results.log
make[3]: *** [CMakeFiles/geosx_validate_all_xml_files] Error 1
make[2]: *** [CMakeFiles/geosx_validate_all_xml_files.dir/all] Error 2
make[1]: *** [CMakeFiles/geosx_validate_all_xml_files.dir/rule] Error 2
make: *** [geosx_validate_all_xml_files] Error 2
```

There are a couple of things that you can check here:

1) Look at the log file `xml_validation_results.log` in the build directory.  Any issues with the xml validation tools may show up here.   We are looking for specific keywords in this file, so it is possible that we don't catch a system error.
2) You can also try using one of many xml validation tools (see https://geosx-geosx.readthedocs-hosted.com/en/latest/coreComponents/fileIO/doc/InputValidation.html).  For some of these to work, you may need to add a couple of attributes to your Problem block (pointing to your schema location):

```xml
<Problem xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="/path/to/GEOSX/src/coreComponents/schema/schema.xsd">
...
</Problem>
```

**Comment by cssherman** [comment] 2021-07-23 21:08
@jhuang2601 - Another thought: the xml validation step is run when you build the code.  Normally, people notice the error when the build locally.  It's possible that Travis didn't catch the error properly (this is a bit more difficult to debug)

**Comment by jhuang2601** [comment] 2021-07-23 21:11
@cssherman What am asking is to find a way to avoid this potential issue when locally preparing and running the xml file. Then, we won't face this failure when pulling the PR and building the main code.

**Comment by TotoGaz** [comment] 2021-07-23 21:30
> Normally, people notice the error when the build locally.

Normal users do not build, they use 😉

@cssherman Is there a way to validate a file through the command line (`xmllint --schema ... `)?

**Comment by cssherman** [comment] 2021-07-23 21:31
@jhuang2601 in that case, I'd recommend using one of the other xml tools to validate a file before running it.  The one I personally use is a plugin for Sublime text called Exalt (see the documentation link, format from before).  If you have the schema location set appropriately, then if you make a mistake, then it will be automatically highlighted.  For example:

![image](https://user-images.githubusercontent.com/4932756/126843301-b1c36e9d-ee5e-4d0e-8dc2-75e9b6b512ab.png)


Note that the xml parser within GEOSX does not validate the schema before it uses it.  If it were to contain an error, then it would show up as another type of error when it is accessed.

**Comment by cssherman** [comment] 2021-07-23 21:32
@TotoGaz - Yes, you could use a couple of different command line tools as well, such as xmllint (which should be installed on a typical system) or the preprocess_xml tool that we optionally build alongside GEOSX.

**Comment by klevzoff** [comment] 2021-07-23 21:33
My understanding: there are no problems with schema-based validation, it works and it catches issues on Travis with any file committed to the repo, as well as locally pre-commit (assuming one runs a full build). The problem @jhuang2601 is referring to is that GEOSX actually allows more relaxed input than the schema prescribes (skipping the `{` and `}` delimiters when reading tensors). These lines are the core of the issue:
https://github.com/GEOSX/GEOSX/blob/6537dd0fd7d0b5d932c031b6cd706d05ab0b81a5/src/coreComponents/dataRepository/xmlWrapper.cpp#L32-L35

**Comment by klevzoff** [comment] 2021-07-23 21:39
Or are we talking about the old argument of git-based vs all-files-in-source-tree validation? We ended up doing git-based by default, which means if you haven't _added_ the new XML to git when you do the local build, it won't validate the new file. I thought it's a reasonable approach, but maybe we can revisit.

**Comment by jhuang2601** [comment] 2021-07-23 21:41
@klevzoff You're absolutely right. I just notice another similar issue for `targetExactTimestep`. GEOSX allows relaxed input and runs the case without any issue. But when making the pull of PRs, Travis imposes a more strict check on xml inputs and reports failure.

**Comment by jhuang2601** [comment] 2021-07-23 21:48
> > Normally, people notice the error when the build locally.
> 
> Normal users do not build, they use 😉
> 
> @cssherman Is there a way to validate a file through the command line (`xmllint --schema ... `)?

Right, I'm a normal user

**Comment by TotoGaz** [comment] 2021-07-23 21:51
@klevzoff I believe it's just that @jhuang2601 is not (yet?) a developer and therefore does not build `geosx`.
And when building an input file "_from scratch_", this new file never goes through the building validator in the build.
That's legit.

If we manage to provide the proper command line for validation outside the building process (like @cssherman does in sublime text or using `validateXMLFiles.bash`) then we are OK.

@jhuang2601 running `xmllint --schema schema.xsd my_file.xml` should be OK.

**Comment by jhuang2601** [comment] 2021-07-23 21:57
@TotoGaz just try the command line and receive this error message
```
warning: failed to load external entity "schema.xsd"
Schemas parser error : Failed to locate the main schema resource at 'schema.xsd'.
WXS schema schema.xsd failed to compile
```

**Comment by TotoGaz** [comment] 2021-07-23 21:59
Yes, You need to generate the schema first `./geosx -s schema.xsd` which will generate some `schema.xsd` file that you can use afterwards.
But I must confess it's crashing on my box... 😢

**Comment by cssherman** [comment] 2021-07-23 21:59
@TotoGaz @klevzoff @jhuang2601 @joshua-white - This discussion may be suited more for a conversation.  I've opened one here with some additional thoughts: #1516

**Comment by cssherman** [comment] 2021-07-23 22:04
@TotoGaz - the schema construction step crashing is concerning, and I can confirm that is broken for develop:

```
Received signal 11: Segmentation fault

** StackTrace of 11 frames **
Frame 0: /lib64/libc.so.6 
Frame 1: std::_Hashtable<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, long>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, long> >, std::__detail::_Select1st, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::find(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const 
Frame 2: geosx::constitutive::MultiFluidBase const& geosx::dataRepository::Group::getGroup<geosx::constitutive::MultiFluidBase, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const 
Frame 3: geosx::CompositionalMultiphaseBase::registerDataOnMesh(geosx::dataRepository::Group&) 
Frame 4: geosx::dataRepository::Group::registerDataOnMeshRecursive(geosx::dataRepository::Group&) 
Frame 5: geosx::dataRepository::Group::registerDataOnMeshRecursive(geosx::dataRepository::Group&) 
Frame 6: geosx::dataRepository::Group::registerDataOnMeshRecursive(geosx::dataRepository::Group&) 
Frame 7: geosx::ProblemManager::generateDocumentation() 
Frame 8: geosx::GeosxState::initializeDataRepository() 
Frame 9: main 
Frame 10: __libc_start_main 
Frame 11: /g/g17/sherman/GEOS/geosx/GEOSX/build-quartz-gcc@8.1.0-release/bin/geosx 
=====
```

The schema generation does require the code to build a complete skeleton of its data structure, so it can certainly any undetected issues.  I'll open a bug report and do some digging...

**Comment by cssherman** [comment] 2021-07-23 22:05
@jhuang2601 - in the meantime, a version of the schema file is in the GEOSX source code: `GEOSX/src/coreComponents/schema/schema.xsd`

**Comment by TotoGaz** [comment] 2021-07-23 22:09
@cssherman Most likely generating the schemes will become a critical part of what we provide to the users.
We must check that it's working as part of our tests then.

**Comment by cssherman** [comment] 2021-07-23 22:13
@TotoGaz - Agreed.  I'm surprised that the build didn't detect an issue here.  As a side-note, among other reasons, we commit the automatically generated schema to have access to the git history

**Comment by klevzoff** [comment] 2021-07-23 22:18
The schema crash started happening after https://github.com/GEOSX/GEOSX/pull/1512 was merged, but we didn't catch it, because the script that runs the schema build does not process errors from its subcommands:
https://github.com/GEOSX/GEOSX/blob/6537dd0fd7d0b5d932c031b6cd706d05ab0b81a5/scripts/updateRstTables.bash#L7-L8

**Comment by cssherman** [comment] 2021-07-23 22:22
@klevzoff - Agreed, I noticed the same issue just now

**Comment by joshua-white** [comment] 2021-07-29 17:19
Closing, will open separate issue on making R1 tensor parsing consistent.

**Closed by joshua-white** 2021-07-29 17:19 UTC
Labels: priority: low, triaging
