### ISSUE TITLE
A problem about Partitioning the model with METIS

### ISSUE THREAD

**Issue by Ron-Wang** [GEOSX/GEOSX#1719] opened 2022-01-03 15:13 UTC
**Describe the bug**
A problem about Partitioning the model with METIS

**Expected behavior**
I used "mpirun -n 3 /home/ron18/GEOSX/GEOSX/build-your-platform-release/bin/geosx -i Test.xml" (with the external mesh), but it said that something is wrong when partitioning. 

**Screenshots**
![image](https://user-images.githubusercontent.com/18233013/147946480-e2fc5973-66bb-4d2a-b283-8d6f2dda3285.png)

**Platform (please complete the following information):**
- Machine [e.g. LLNL/Quartz] 
- Compiler: [e.g. gcc 8.1.0]
- GEOSX Version [e.g. 0.2]

**Comment by joshua-white** [comment] 2022-01-06 17:57
@Ron-Wang, would you mind providing a copy of the mesh?

**Comment by Ron-Wang** [comment] 2022-01-09 11:08
Thank you very much for your reply. 
(1) Our mesh is as follows and it failed to run with 3 parallel threads in my computer (The system is in Ubuntu18.04).
(2) I tried my colleague's CentOS7.9 server and found that it can run successfully. I wonder may the system or some libs causes the bug. 
(3) I currently install CentOS7.9 and GEOSX in my computer, and find the following problems:
![image](https://user-images.githubusercontent.com/18233013/148679633-a708dd22-af6f-4c4e-8da0-64316333ceef.png)

**Comment by Ron-Wang** [comment] 2022-01-09 12:07
[https://cloud.tsinghua.edu.cn/f/1fff953c31254864a74f/?dl=1](url)
The mesh file

**Comment by Ron-Wang** [comment] 2022-01-10 03:39
@joshua-white I guess the bug may occurs because of different versions of gcc. I used gcc-8.4.0 in Ubuntu18.04, which has this bug. I am trying to use gcc-8.1.0 to test.

**Comment by Ron-Wang** [comment] 2022-01-24 07:02
@joshua-white I develop the "ExplicitTransient" of SinglePhaseFVM and the "Explicit Method" of Hydrofracture (following @huang40 ), i wonder if I can pull a require of this. I have met some problem of pointer or buffer when i use large-scale model. Thanks a lot!

**Comment by joshua-white** [comment] 2022-01-24 22:14
Hey @Ron-Wang, could you provide a little more detail on what you would like to do?  Your comment above is a little cryptic.

As a side note, an explicit transient integration algorithm for SinglePhaseFVM will have a very severe time-step restriction for stable integration.

**Comment by Ron-Wang** [comment] 2022-01-25 09:01
@joshua-white I am so sorry that I did not make that quite clear.
Actually, I use ExplicitDynamic of SolidMechanics_LagrangianFEM to gain the deformation and update the porosity. And I use ExplicitTransient of SinglePhaseFVM (which is abandoned in the develop branch) to gain the pressure. 
the "Explicit Method" in HydrofractureSolver means that: 
(I) The pressures from SinglePhaseFVM , are added to the node forces when solving the Balance Equation in SolidMechanics_LagrangianFEM. 
(II) The porosities from SolidMechanics_LagrangianFEM , are updated in SinglePhaseFVM.

**Comment by Ron-Wang** [comment] 2022-01-25 09:07
@joshua-white I have installed the last version GEOSX and find that massDamping is not used in ExplicitDynamic of SolidMechanicsLagrangianFEM as following: 
the new version: 
![image](https://user-images.githubusercontent.com/18233013/150945890-9eaba95e-cbc1-460a-9510-ed2b3d815cb8.png)
the old version: 
![image](https://user-images.githubusercontent.com/18233013/150945975-fc991c70-60e2-4ec9-a528-3d0befe07897.png)
I wonder if there is some bug in it? Thank you so much!

**Comment by TotoGaz** [comment] 2023-02-10 16:57
Our way of dealing with this kind of issues have completely changed.
The input file not being available anymore, I'm closing the issue.
Please (re)open an issue if the problem is still there.
Thank you for your understanding!

**Closed by TotoGaz** 2023-02-10 16:57 UTC
Labels: type: bug
