### ISSUE TITLE
Partitioning- and platform-dependent failures in multiple physics solvers

### ISSUE THREAD

**Issue by joshua-white** [GEOSX/GEOSX#2173] opened 2022-11-22 03:39 UTC
Users on several platforms have noticed the certain solvers will fail when a certain number of MPI ranks are requested, but not before.  The critical partitioning scenario seems to be platform dependent, and the problem has not year been reproduced on LLNL systems.  We have a consistent reproducer (`co2_thermal_3d.xml`) that fails on at least five different non-LLNL systems and that can be shared as needed.  Errors are slightly different on different systems, but often seem to related to the ghost maps as they are being set up.

On Sherlock (at Stanford), it has been observed that the number of MPI ranks on a node matters.  It will run with 64 ranks / 1 node, but fail for 64 ranks / 4 nodes.

On LLNL systems, the problem will fail if enough ranks are requested to create a single layer of elements on a given rank, but this may be an unrelated issue associated with neighbors-of-neighbors maps.  We mention it here just in case it proves relevant.

**Comment by joshua-white** [comment] 2022-11-22 03:57
@jafranc Can you do a few more tests to examine the under-subscribed node behavior?  Also, do you have OpenMP enabled?

**Comment by rrsettgast** [comment] 2022-11-22 05:41
@joshua-white What is meant by `cores`? Do you mean `ranks`?

**Comment by jafranc** [comment] 2022-11-22 16:26
I do have OpenMP enabled. I will report test here.

**Comment by joshua-white** [comment] 2022-11-22 17:02
@rrsettgast yes, sorry, ranks not cores.  I'll edit the issue description above for clarity.

**Comment by TotoGaz** [comment] 2022-11-28 17:02
I assume that the `cellBlock` is made of hexs since it's supposed to have `12` edges?
Is it breaking because of the `12`?
Are you able to spot where the involved cell is? Near ghost zones?

**Comment by joshua-white** [comment] 2022-11-29 16:30
@TotoGaz, after much digging, I think the edge map issue above is completely unrelated.  It looks like a subtle issue in the input mesh, not the code itself.  I jumped the gun when I saw the  `_Map_base::at` error pop up again.  Anyway, this may be another motivation for a rigorous mesh checking utility.

If I can find time today, I will try to reproduce @jafranc's experiments above on Quartz.

**Comment by TotoGaz** [comment] 2022-11-29 16:39
> Anyway, this may be another motivation for a rigorous mesh checking utility.

Good to know. Could `mesh_doctor` detect the issue?

**Comment by kjdugan** [comment] 2022-12-28 21:41
@joshua-white and myself were looking at this problem earlier and realized that there are multiple `mpi_wait` calls being using in the neighbor communication methods, which seem to be interfering with each other. The fix in the above pull request puts an `mpi_barrier` after these calls to `mpi_wait` which should approximate a `wait_all`. The important point is that the barriers isolate the multiple calls to `mpi_wait` -- resolving the errors shown in spe10 and other simulations.

This is certainly a short-term solution. Would love to open up a discussion on the overall async strategy used.
@wrtobin @corbett5

**Comment by wrtobin** [comment] 2022-12-28 21:51
@kjdugan 

Presumably between [CommunicationTools.cpp#L690](https://github.com/GEOSX/GEOSX/blob/develop/src/coreComponents/mesh/mpiCommunications/CommunicationTools.cpp#L690) and [CommunicationTools.cpp#L696](https://github.com/GEOSX/GEOSX/blob/develop/src/coreComponents/mesh/mpiCommunications/CommunicationTools.cpp#L696)?

As we do prior to that at [CommunicationTools.cpp#L669](https://github.com/GEOSX/GEOSX/blob/develop/src/coreComponents/mesh/mpiCommunications/CommunicationTools.cpp#L669)

That should be totally fine functionally.
If we encounter any performance impact to the ghost setup there are alternatives (as noted in that same comment).

**Comment by joshua-white** [comment] 2022-12-28 21:59
@jafranc, when you get a chance, could you see if this fixes your issues on Sherlock?

**Comment by rrsettgast** [comment] 2022-12-29 01:26
@wrtobin Are we not utilizing the tags properly to avoid this?

**Comment by wrtobin** [comment] 2022-12-29 16:41
@rrsettgast 
We only currently use tags in the `NeighborCommunicator` to differentiate between e.g. the sends/recvs for sizes and the sends/recvs for data, but not calls from different communication phase-groups  (calls to an `activeWait` function with multiple phases provided).

Having multiple communication phase-groups take place without a sync between them **can** cause processes to miscommunicate  -- depending on which active wait function is used -- since they have different sync characteristics. Previously we'd only encountered them nondeterministically (hence the barrier in `setupGhosts` to prevent it entirely), but I suppose depending on changes to MPI sync outside of the currently analyzed scope, mesh partitioning structure, and MPI implementation, it could be deterministic for particular problems on specific platforms. 

In lieu of reworking our use of tags immediately, we can also take the send requests from the `postSend` calls and return those from the last phase (`rebuildSyncLists`) of these phase-groups, then add an additional null-phase which just returns MPI_REQUEST_NULL. That *should* prevent this issue, though it is effectively identical to an `MPI_iBarrier`, which might be the more obvious way to fix things since it is more obvious to a developer what is going on instead of recreating a sync operation in a non-obvious manner.

We can eventually also just remove the size send/recv phase and use dynamic recv-ing with `MPI_Probe` to eliminate a phase from most of our phase-groups, since sending buffer sizes around isn't actually necessary as MPI already does this under the hood to recv the buffer in the first place.

**Comment by rrsettgast** [comment] 2022-12-30 03:57
@wrtobin So we are able to start a new communication phase prior to finishing the previous phase? I.e. Why are we able to proceed if all `MPI_Status` and `MPI_Request` associated with at `MPI_iCommData` are not completed?

**Comment by rrsettgast** [comment] 2023-01-01 18:00
@joshua-white where is the `co2_thermal_3d.xml` located? I can't seem to find it.

**Comment by joshua-white** [comment] 2023-01-01 18:37
@rrsettgast: I'll share offline.  It is not yet in the repo.

**Comment by jafranc** [comment] 2023-01-02 01:24
@joshua-white I can confirm that the fixe solves the crash on _sherlock_ too. (tested on 4 nodes x 64 ranks/32 ranks and 1 node x 32 ranks)

**Closed** 2023-01-04 08:05 UTC
Labels: type: bug

**Comment by TotoGaz** [comment] 2023-01-09 18:27
Congratulations for fixing this bug guys!
